# Generated by Django 2.2.1 on 2019-05-12 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1524)),
                ('rooms', models.IntegerField()),
                ('size', models.FloatField(max_length=255)),
                ('price', models.IntegerField()),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_ssn', models.IntegerField()),
                ('owner_phone', models.IntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZIP',
            fields=[
                ('zip', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.ApartmentCategory'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='seller',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='zip',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.ZIP'),
        ),
    ]
