# Generated by Django 2.2.1 on 2019-05-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [



        migrations.AddField(
            model_name='apartment',
            name='zip',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.ZIP'),
        ),
    ]
