# Generated by Django 2.2.1 on 2019-05-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='owner_ssn',
            field=models.BigIntegerField(),
        ),
    ]
