# Generated by Django 2.2.1 on 2019-05-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zip',
            name='id',
        ),
        migrations.AlterField(
            model_name='zip',
            name='zip',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
