# Generated by Django 2.2.1 on 2019-05-14 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartment', '0002_auto_20190513_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='buyer',
        ),
        migrations.CreateModel(
            name='ApartmentSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('property', models.CharField(max_length=255)),
                ('size_from', models.IntegerField()),
                ('size_to', models.IntegerField()),
                ('price_from', models.IntegerField()),
                ('price_to', models.IntegerField()),
                ('rooms_from', models.IntegerField()),
                ('rooms_to', models.IntegerField()),
                ('zip', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
