# Generated by Django 2.2.1 on 2019-05-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_auto_20190505_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='owner_name',
            field=models.CharField(default='Valgeir', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner_phone',
            field=models.IntegerField(default=1234567),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner_ssn',
            field=models.IntegerField(default=1122334455),
            preserve_default=False,
        ),
    ]
