# Generated by Django 2.2.1 on 2019-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_auto_20190511_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='buyer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
