# Generated by Django 2.2.1 on 2019-05-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_auto_20190505_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.CharField(max_length=1524),
        ),
    ]
