# Generated by Django 2.2.1 on 2019-05-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_auto_20190514_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsearch',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='apartmentsearch',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartmentsearch',
            name='price_from',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartmentsearch',
            name='price_to',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartmentsearch',
            name='property',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='apartmentsearch',
            name='rooms_from',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartmentsearch',
            name='rooms_to',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartmentsearch',
            name='size_from',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartmentsearch',
            name='size_to',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartmentsearch',
            name='zip',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
