# Generated by Django 2.2.1 on 2019-05-12 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartment', '0004_auto_20190511_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='buyer_id',
        ),
        migrations.AddField(
            model_name='apartment',
            name='buyer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
