# Generated by Django 2.2.1 on 2019-05-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_auto_20190514_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsearch',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
