# Generated by Django 2.2.1 on 2019-05-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_auto_20190514_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentsearch',
            old_name='category',
            new_name='category_name',
        ),
    ]
