# Generated by Django 2.2.1 on 2019-05-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_auto_20190514_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentsearch',
            old_name='category_name',
            new_name='category',
        ),
    ]
