# Generated by Django 2.2.1 on 2019-05-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_remove_apartmentsearch_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsearch',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment'),
        ),
    ]
