# Generated by Django 2.2.1 on 2019-05-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_apartmentsearch_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentsearch',
            name='apartment',
        ),
        migrations.AlterField(
            model_name='apartmentsearch',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
