# Generated by Django 2.2.1 on 2019-05-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0013_auto_20190515_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsearch',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
