# Generated by Django 2.2.1 on 2019-05-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0014_auto_20190515_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsearch',
            name='order_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
