# Generated by Django 2.2.1 on 2019-05-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.CharField(blank=True, max_length=1999),
        ),
    ]
