# Generated by Django 2.2.1 on 2019-05-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20190517_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.CharField(default='email@email.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(default=123455, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SellerImage',
        ),
    ]
