# Generated by Django 2.2.1 on 2019-05-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20190509_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.CharField(blank=True, max_length=2999),
        ),
    ]
