# Generated by Django 2.2.1 on 2019-05-12 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num_1', models.DecimalField(decimal_places=0, max_digits=4)),
                ('card_num_2', models.DecimalField(decimal_places=0, max_digits=4)),
                ('card_num_3', models.DecimalField(decimal_places=0, max_digits=4)),
                ('card_num_4', models.DecimalField(decimal_places=0, max_digits=4)),
                ('cvc', models.DecimalField(decimal_places=0, max_digits=3)),
                ('expire', models.DateTimeField()),
                ('cardholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
