# Generated by Django 2.2.1 on 2019-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expire',
            field=models.DateField(),
        ),
    ]
