# Generated by Django 2.2.1 on 2019-05-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190512_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cc_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cc_expiry',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cc_number',
        ),
    ]
