# Generated by Django 2.2.1 on 2019-05-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_auto_20190513_1406'),
        ('user', '0010_auto_20190513_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='apartment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment'),
            preserve_default=False,
        ),
    ]
