# Generated by Django 2.2.1 on 2019-05-13 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_sale_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='apartment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cardholder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
